package com.shahabkondri.chatgpt.api.model;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Enum representing the role of the message sender in the ChatGPT API.
 *
 * @author Shahab Kondri
 */
public enum MessageRole {

	/**
	 * A system-generated message, providing instructions or context for the conversation.
	 */
	SYSTEM("system"),

	/**
	 * A message authored by the end-user.
	 */
	USER("user"),

	/**
	 * A message generated by the ChatGPT model as a response to user
	 */
	ASSISTANT("assistant");

	@JsonValue
	private final String role;

	MessageRole(String role) {
		this.role = role;
	}

	/**
	 * Retrieves the role of the message sender in the ChatGPT API.
	 * @return A String representing the role of the message sender, which can be one of
	 * the following: "system", "user", or "assistant".
	 */
	public String getRole() {
		return role;
	}

}
